version: '3.8'

services:
  ssh-tunnel:
    image: alpine:latest
    environment:
      - SSH_HOST=pma.letareau.fr
      - SSH_USER=leop
      - SSHPASS=m2-leop
    command: >
      sh -c "apk add --no-cache openssh-client sshpass && sshpass -e ssh -o StrictHostKeyChecking=no -N -L 0.0.0.0:3307:localhost:3306 $$SSH_USER@$$SSH_HOST"
    networks:
      - meetmybar-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # Modifié pour pointer vers le tunnel SSH local
      - SPRING_DATASOURCE_URL=jdbc:mariadb://ssh-tunnel:3307/meetmybar
      - SPRING_DATASOURCE_USERNAME=leop
      - SPRING_DATASOURCE_PASSWORD=m2tiila-leop
    depends_on:
      - redis
      - ssh-tunnel  # Ajout de la dépendance au tunnel SSH
    networks:
      - meetmybar-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - meetmybar-network

networks:
  meetmybar-network:
    driver: bridge