services:
  ssh-tunnel:
    image: alpine:latest
    environment:
      - SSH_HOST=${SSH_HOST}
      - SSH_USER=${SSH_USER}
      - SSHPASS=${SSH_PASSWORD}
    command: >
      sh -c "apk add --no-cache openssh-client sshpass && sshpass -e ssh -o StrictHostKeyChecking=no -N -L 0.0.0.0:3307:localhost:3306 $$SSH_USER@$$SSH_HOST"
    networks:
      - meetmybar-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mariadb://ssh-tunnel:3307/meetmybar
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - redis
      - ssh-tunnel
    networks:
      - meetmybar-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - meetmybar-network

networks:
  meetmybar-network:
    driver: bridge