version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mariadb://pma.letareau.fr:3306/meetmybar
      - SPRING_DATASOURCE_USERNAME=leop
      - SPRING_DATASOURCE_PASSWORD=m2tiila-leop
    depends_on:
      - redis
    networks:
      - meetmybar-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - meetmybar-network

networks:
  meetmybar-network:
    driver: bridge
