openapi: 3.1.0
x-stoplight:
  id: pix187dc4bd47
info:
  title: meetMyBarSwagger
  version: '1.0'
  summary: Meet my bar
  description: "Meet My Bar est une application mobile Android qui permet de repérer les bars autour de soi et d'avoir des informations pratiques comme le prix de la bière la moins chère. Il sera possible de rechercher un bar par son nom, par un type de bière ou par tranche de prix pour les bières. Il est possible de se connecter  et de remplir ses infos personnelles et d'ajouter des amis sur l'application. Ajouter des amis permet d'avoir accès à leur favori et d'être ajouté à des événements créés pour une sortie dans un des bars présents. Les bars possèdent des évènements où l'utilisateur peut choisir si l'événement est visible par tous ou seulement pas ses invités ( au sein de ses amis ). Un événement est propre à un bar et à une date et heure précise. L'application est renseignée par ses utilisateurs, chaque user peut créer un bar et renseigner les informations qui lui correspondent, il est ensuite disponible pour les autres utilisateurs.\r\nIl peut également mettre à jour les données du bar avec le nouveaux prix de la bière, ses horaires d'ouverture/fermeture.\r\n"
  contact:
    name: ''
servers:
  - url: 'http://localhost:8080'
    description: ''
paths:
  '/bar/{barId}':
    parameters:
      - schema:
          type: integer
        name: barId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bar'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-bar-barId
      x-stoplight:
        id: s3d2zezptq514
    delete:
      summary: Your DELETE endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bar'
      operationId: delete-bar-barId
      x-stoplight:
        id: c5kxfbefb49go
  '/bar/address/{barAddress}':
    parameters:
      - schema:
          type: string
        name: barAddress
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bar'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-bar-address-barAddress
      x-stoplight:
        id: qq3i0jznb6fuh
  /bar:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bar'
                  x-stoplight:
                    id: bnm754kk8srae
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-bar
      x-stoplight:
        id: 0upzwgd4i0pp2
    post:
      summary: Your POST endpoint
      tags: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bar'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: post-bar
      x-stoplight:
        id: pgz3nkb1kwpiv
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bar'
    patch:
      summary: Your PATCH endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bar'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: patch-bar
      x-stoplight:
        id: w6ypycukj2i37
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bar'
  /drink:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Drink'
                  x-stoplight:
                    id: 1hhzgtmz8glt7
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-drink
      x-stoplight:
        id: azpwkc6to7yjk
    post:
      summary: Your POST endpoint
      tags: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Drink'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: post-drink
      x-stoplight:
        id: 3xhugknok8mz9
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Drink'
    patch:
      summary: Your PATCH endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Drink'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: patch-drink
      x-stoplight:
        id: 6fcbfsf1u8fds
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Drink'
  '/drink/{drinkId}':
    parameters:
      - schema:
          type: integer
        name: drinkId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Drink'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-drink.-drinkName
      x-stoplight:
        id: 6tyqiqc517buq
    delete:
      summary: Your DELETE endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Drink'
      operationId: delete-drink-drinkId
      x-stoplight:
        id: dnfobti44jfqy
  '/bar/name/{barName}':
    parameters:
      - schema:
          type: string
        name: barName
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bar'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-bar-name-barName
      x-stoplight:
        id: 5qva8tssmloqf
  '/drink/name/{drinkName}':
    parameters:
      - schema:
          type: string
        name: drinkName
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Drink'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      operationId: get-drink-name-drinkName
      x-stoplight:
        id: hu39hretcrslt
  /scheduleday:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScheduleDay'
                  x-stoplight:
                    id: u1osbho2do65j
      operationId: get-scheduleday
      x-stoplight:
        id: ibbw44caqt6v7
    post:
      summary: Your POST endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleDay'
      operationId: post-scheduleday
      x-stoplight:
        id: mrpx4t6mjgagq
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleDay'
    patch:
      summary: Your PATCH endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleDay'
      operationId: patch-scheduleday
      x-stoplight:
        id: 8agh6ziqztj95
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleDay'
  '/scheduleday/{scheduledayId}':
    parameters:
      - schema:
          type: integer
        name: scheduledayId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleDay'
      operationId: get-scheduleday-scheduledayId
      x-stoplight:
        id: d8bvd64j475cl
    delete:
      summary: Your DELETE endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleDay'
      operationId: delete-scheduleday-scheduledayId
      x-stoplight:
        id: d5c8ca97vpl17
  '/photos/download/bar/{id}':
    get:
      summary: Télécharger les photos d'un bar
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Photos téléchargées avec succès
          content:
            application/octet-stream:
              schema:
                type: array
                items:
                  type: string
                  format: binary
        '500':
          description: Erreur serveur interne
components:
  schemas:
    Bar:
      title: Bar
      type: object
      examples:
        - id: 142
          address: 6 Route Du Chef
          name: Shark
          capacity: 25
      x-stoplight:
        id: z076sc40zdbdt
      x-tags:
        - Bar
      required:
        - id
      properties:
        id:
          type: integer
          description: Unique identifier for the given bar.
          x-stoplight:
            id: wonyzzti5q0ss
        address:
          type: string
          x-stoplight:
            id: 4k4461y58okcd
        name:
          type: string
          x-stoplight:
            id: 5mh5bgchto6fy
        capacity:
          type: integer
          x-stoplight:
            id: yejdq4vn0v3np
        drinks:
          type: array
          x-stoplight:
            id: obkbbdzvowldn
          items:
            $ref: '#/components/schemas/Drink'
            x-stoplight:
              id: afrjk37mforve
        planning:
          type: array
          x-stoplight:
            id: ekwtg1qiijrc6
          items:
            $ref: '#/components/schemas/ScheduleDay'
            x-stoplight:
              id: u3lwe13hr1wh4
        city:
          type: string
          x-stoplight:
            id: lz18rr0nola3j
        postal_code:
          type: string
          x-stoplight:
            id: 7w948nf8g5gtg
    Drink:
      title: Drink
      x-stoplight:
        id: sgpqj4r6lfb75
      type: object
      x-tags:
        - drink
      required:
        - id
      properties:
        id:
          type: integer
          x-stoplight:
            id: 0av3dcnadccfo
        alcohol_degree:
          type: number
          x-stoplight:
            id: wbg1e7uw78w95
        name:
          type: string
          x-stoplight:
            id: hj2pc69610sz3
        brand:
          type: string
          x-stoplight:
            id: drvto8xezd3ea
        type:
          x-stoplight:
            id: j45cpny5ttlvr
          enum:
            - biere_blonde
            - biere_rouge
            - biere_ambre
            - biere_noire
            - biere_blanche
            - biere_brune
            - vin_rouge
            - vin_blanc
            - vin_rose
            - non_defini
    ScheduleDay:
      title: ScheduleDay
      x-stoplight:
        id: ytqkoxbmqj72p
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          x-stoplight:
            id: 6mjqgysu9blaw
        opening:
          type: string
          x-stoplight:
            id: r4634yg0zvq33
          format: time
        closing:
          type: string
          x-stoplight:
            id: 43z3lkomwtfef
          format: time
        day:
          type: string
          x-stoplight:
            id: 8782w7jjdne9q
