name: Deploy to Production

on:
  push:
    branches:
      - main  # ou master, ou toute autre branche que vous souhaitez surveiller

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Configurer le répertoire Git comme sûr
            sudo git config --global --add safe.directory ${{ secrets.PROJECT_PATH }}
            
            # Se déplacer dans le répertoire du projet
            cd ${{ secrets.PROJECT_PATH }}
            
            # Pull des changements
            sudo git pull
            
            # Utiliser docker compose (nouvelle syntaxe sans tiret)
            sudo docker compose down
            sudo docker compose build
            sudo docker compose up -d