name: Deploy to Production

on:
  push:
    branches:
      - main  # ou master, ou toute autre branche que vous souhaitez surveiller

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull
            docker-compose down
            docker-compose build
            docker-compose up -d 